import { AppProviders } from '@/providers';
import '../globals.css';
import { AppBreadcrumb } from '@/components/app-breadcrumb';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/app/(tutor)/tutor/components/app-sidebar';
import { Toaster } from 'sonner';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<AppProviders>
					<SidebarProvider>
						<AppSidebar />
						<main className='p-4 w-full'>
							<div className='flex items-center mb-4'>
								<SidebarTrigger />
								<AppBreadcrumb />
							</div>
							{children}
							<Toaster />
						</main>
					</SidebarProvider>
				</AppProviders>
			</body>
		</html>
	);
}
