import { AppProviders } from '@/providers';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { AppBreadcrumb } from '@/components/app-breadcrumb';
import { Toaster } from '@/components/ui/sonner';
import { Nunito } from 'next/font/google';
import '../globals.css';

const inter = Nunito({ subsets: ['latin'], weight: ['300', '400', '500', '700', '900'] });

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AppProviders>
					<SidebarProvider>
						<AppSidebar />
						<main className='p-4 w-full'>
							<div className='flex items-center mb-4'>
								<SidebarTrigger />
								<AppBreadcrumb />
							</div>
							{children}
							<Toaster richColors />
						</main>
					</SidebarProvider>
				</AppProviders>
			</body>
		</html>
	);
}
