import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { AppProviders } from '@/providers';

const poppins = Manrope({
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html>
			<body className={poppins.className}>
				<AppProviders>{children}</AppProviders>
			</body>
		</html>
	);
}
