import type { Metadata } from 'next';
import { Ruda } from 'next/font/google';
import '../globals.css';
import Header from '@/app/layout/header';
import { AppProviders } from '@/providers';
import Footer from '@/app/layout/footer';
import ScrollToTop from '@/components/scroll-to-top';

const poppins = Ruda({
	weight: ['400', '500', '600', '700', '800', '900'],
	subsets: ['latin', 'cyrillic', 'vietnamese', 'latin-ext'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html>
			<body className={poppins.className}>
				<AppProviders>
					<Header />
					{children}
					<Footer />
					<ScrollToTop showBelow={400} right={25} bottom={75} />
				</AppProviders>
			</body>
		</html>
	);
}
